#! /bin/bash

repo="$1"
post_receive_hook_script="$(dirname $0)/pushand_post-receive_hook"

if [[ ! -d "$repo" ]]; then
	go_back="$(pwd)"
	mkdir -pv "$repo" > /home/git/pushand.log
	cd "$repo"
	git init --bare > /home/git/pushand.log
	cd "$go_back"
fi

# make the real call to the real git-receive-pack
# TODO make this dynamic!  using the pushand_server_variables
/usr/bin/git-receive-pack_original/git-receive-pack $*
